plugins {
    id 'com.android.application'
}

android {
    namespace = 'im.ews.zealot.example'
    compileSdk = 37

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        minSdk = 23
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"

        applicationId = "im.ews.zealot.example"
    }
    buildTypes {
        release {
            minifyEnabled = true
            proguardFiles(getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro')
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

}

dependencies {
    implementation project(":zealot")
    implementation 'androidx.appcompat:appcompat:1.8.0'
}
